name = "A3 Antistasi";
author = "Antistasi Dev Team";
logo = "";
logoOver = "";
logoSmall = "antistasi_logo_small.paa";
picture = "antistasi_overview.paa";
description = "";
tooltip = "Antistasi";
tooltipOwned = "Antistasi";
overview = ""<br/><t align='center' size='0.75'>Visit Antistasi on our <t href='https://antistasi.de/'>Website</t> | <t href='http://antistasi.de/discord'>Discord</t> | <t href='https://twitter.com/antistasio'>Twitter</t></t><br/><br/>";
actionName = "GitHub";
action = "https://github.com/official-antistasi-community/A3-Antistasi";
