/*
Maintainer: DoomMetal
    Contains defines for texture paths.

    Examples:
    Getting textures from arma: "\a3\3DEN\Data\Controls\ctrlDefault\arrowEmpty_ca.paa)
    Getting textures from mission: QTexturePathOf(icon_undercover.paa)

*/

// Defines for texture paths
// Arma paths example: "\a3\3DEN\Data\Controls\ctrlDefault\arrowEmpty_ca.paa)
// Mission paths example: QTexturePathOf(icon_undercover.paa)

#ifndef INCLUDED_DEFINES_HPP
    #include "defines.hpp"
#endif

#define A3A_ArrowEmpty_1L           QTexturePathOf(arrowEmpty_1L.paa)
#define A3A_ArrowEmpty_1R           QTexturePathOf(arrowEmpty_1R.paa)
#define A3A_ArrowEmpty_2L           QTexturePathOf(arrowEmpty_2L.paa)
#define A3A_ArrowEmpty_2R           QTexturePathOf(arrowEmpty_2R.paa)
#define A3A_ArrowEmpty_3L           QTexturePathOf(arrowEmpty_3L.paa)
#define A3A_ArrowEmpty_3R           QTexturePathOf(arrowEmpty_3R.paa)
#define A3A_ArrowFull_1L            QTexturePathOf(arrowFull_1L.paa)
#define A3A_ArrowFull_1R            QTexturePathOf(arrowFull_1R.paa)
#define A3A_ArrowFull_2L            QTexturePathOf(arrowFull_2L.paa)
#define A3A_ArrowFull_2R            QTexturePathOf(arrowFull_2R.paa)
#define A3A_ArrowFull_3L            QTexturePathOf(arrowFull_3L.paa)
#define A3A_ArrowFull_3R            QTexturePathOf(arrowFull_3R.paa)
#define A3A_Icon_AA_Truck           QTexturePathOf(icon_aa_truck.paa)
#define A3A_Icon_Add_Garrison       QTexturePathOf(icon_add_garrison.paa)
#define A3A_Icon_AI_Management      QTexturePathOf(icon_ai_management.paa)
#define A3A_Icon_Assassination      QTexturePathOf(icon_assassination.paa)
#define A3A_Icon_AT                 QTexturePathOf(icon_at.paa)
#define A3A_Icon_AT_Car             QTexturePathOf(icon_at_car.paa)
#define A3A_Icon_AT_Team            QTexturePathOf(icon_at_team.paa)
#define A3A_Icon_Autorifleman       QTexturePathOf(icon_autorifleman.paa)
#define A3A_Icon_Bomb_Specialist    QTexturePathOf(icon_bomb_specialist.paa)
#define A3A_Icon_Cargo              QTexturePathOf(icon_cargo.paa)
#define A3A_Icon_Carpet_Bombing     QTexturePathOf(icon_carpet_bombing.paa)
#define A3A_Icon_Commander          QTexturePathOf(icon_commander.paa)
#define A3A_Icon_Conquest           QTexturePathOf(icon_conquest.paa)
#define A3A_Icon_Convoy_Ambush      QTexturePathOf(icon_convoy_ambush.paa)
#define A3A_Icon_Destroy            QTexturePathOf(icon_destroy.paa)
#define A3A_Icon_Dismiss            QTexturePathOf(icon_dismiss.paa)
#define A3A_Icon_Driver             QTexturePathOf(icon_driver.paa)
#define A3A_Icon_FastTravel         QTexturePathOf(icon_fasttravel.paa)
#define A3A_Icon_FFV                QTexturePathOf(icon_ffv.paa)
#define A3A_Icon_Garrison           QTexturePathOf(icon_garrison.paa)
#define A3A_Icon_Grenadier          QTexturePathOf(icon_grenadier.paa)
#define A3A_Icon_Gunner             QTexturePathOf(icon_gunner.paa)
#define A3A_Icon_Has_AA             QTexturePathOf(icon_has_aa.paa)
#define A3A_Icon_Has_AT             QTexturePathOf(icon_has_at.paa)
#define A3A_Icon_Has_Mortar         QTexturePathOf(icon_has_mortar.paa)
#define A3A_Icon_Has_Static         QTexturePathOf(icon_has_static.paa)
#define A3A_Icon_HE_Bombs           QTexturePathOf(icon_he_bombs.paa)
#define A3A_Icon_Hide               QTexturePathOf(icon_hide.paa)
#define A3A_Icon_HideVic            QTexturePathOf(icon_hidevic.paa)
#define A3A_Icon_Inf_Squad          QTexturePathOf(icon_inf_squad.paa)
#define A3A_Icon_Inf_Team           QTexturePathOf(icon_inf_team.paa)
#define A3A_Icon_Logistics          QTexturePathOf(icon_logistics.paa)
#define A3A_Icon_Medic              QTexturePathOf(icon_medic.paa)
#define A3A_Icon_MG_Team            QTexturePathOf(icon_mg_team.paa)
#define A3A_Icon_Minefield          QTexturePathOf(icon_minefield.paa)
#define A3A_Icon_Mortar_Team        QTexturePathOf(icon_mortar_team.paa)
#define A3A_Icon_Move_HQ            QTexturePathOf(icon_move_hq.paa)
#define A3A_Icon_Napalm_Bomb        QTexturePathOf(icon_napalm_bomb.paa)
#define A3A_Icon_None               QTexturePathOf(icon_none.paa)
#define A3A_Icon_Pilot              QTexturePathOf(icon_pilot.paa)
#define A3A_Icon_Rescue             QTexturePathOf(icon_rescue.paa)
#define A3A_Icon_Rifleman           QTexturePathOf(icon_rifleman.paa)
#define A3A_Icon_Sniper             QTexturePathOf(icon_sniper.paa)
#define A3A_Icon_Sniper_Team        QTexturePathOf(icon_sniper_team.paa)
#define A3A_Icon_Train_Troops       QTexturePathOf(icon_train_troops.paa)
#define A3A_Icon_Undercover         QTexturePathOf(icon_undercover.paa)
#define A3A_Icon_AP_Minefield       QTexturePathOf(icon_ap_minefield.paa)
#define A3A_Icon_AT_Minefield       QTexturePathOf(icon_at_minefield.paa)
#define A3A_Icon_Town               QTexturePathOf(icon_town.paa)
#define A3A_Icon_Outpost            QTexturePathOf(icon_outpost.paa)
#define A3A_Icon_Airbase            QTexturePathOf(icon_airbase.paa)
#define A3A_Icon_Factory            QTexturePathOf(icon_factory.paa)
#define A3A_Icon_Resource           QTexturePathOf(icon_resource.paa)
#define A3A_Icon_Seaport            QTexturePathOf(icon_seaport.paa)
#define A3A_Icon_Clear_Trees        QTexturePathOf(icon_clear_trees.paa)
#define A3A_Icon_Support            QTexturePathOf(icon_support.paa)

// New map icons
#define A3A_Icon_Map_Blank          QTexturePathOf(icon_map_blank.paa)
#define A3A_Icon_Map_City           QTexturePathOf(icon_map_city.paa)
#define A3A_Icon_Map_Factory        QTexturePathOf(icon_map_factory.paa)
#define A3A_Icon_Map_Resource       QTexturePathOf(icon_map_resource.paa)
#define A3A_Icon_Map_Airport        QTexturePathOf(icon_map_airport.paa)
#define A3A_Icon_Map_Seaport        QTexturePathOf(icon_map_seaport.paa)
#define A3A_Icon_Map_Outpost        QTexturePathOf(icon_map_outpost.paa)
#define A3A_Icon_Map_Roadblock      QTexturePathOf(icon_map_roadblock.paa)
#define A3A_Icon_Map_Watchpost      QTexturePathOf(icon_map_watchpost.paa)
#define A3A_Icon_Map_HQ             QTexturePathOf(icon_map_hq.paa)


// From Arma
#define A3A_Icon_Construct          "\a3\ui_f\data\igui\cfg\cursors\iconRepairVehicle_ca.paa"
#define A3A_Icon_Close              "\A3\ui_f\data\GUI\RscCommon\RscButtonSearch\search_end_ca.paa"
#define A3A_Icon_Back               "\A3\ui_f\data\GUI\RscCommon\RscHTML\arrow_left_ca.paa"
#define A3A_Icon_Remotecontrol      "\a3\modules_f_curator\data\portraitremotecontrol_ca.paa"
#define A3A_Icon_Rearm              "\A3\Ui_f\data\IGUI\Cfg\Actions\reammo_ca.paa"
#define A3A_Icon_Heal               "\A3\ui_f\data\igui\cfg\actions\heal_ca.paa"
#define A3A_Icon_Warning            "\A3\Ui_f\data\Map\Markers\Military\warning_CA.paa"
#define A3A_Icon_GroupUnitCount     "\A3\ui_f\data\igui\cfg\simpleTasks\types\meet_ca.paa"
#define A3A_Select_Marker           "\A3\ui_f\data\IGUI\Cfg\Cursors\selectOver_ca.paa"

// Commander picture
#define A3A_Icon_PlayerCommander    "\A3\Ui_f\data\GUI\Cfg\Ranks\colonel_gs.paa"
#define A3A_Icon_PlayerEligible     "\A3\Ui_f\data\GUI\Cfg\Ranks\colonel_gs.paa"
#define A3A_Icon_PlayerIneligible   QTexturePathOf(icon_ineligible.paa)
