class NavGrid {
    #include "Antistasi_Altis.Altis\navGrid.hpp"
    #include "Antistasi_cam_lao_nam.cam_lao_nam\navGrid.hpp"
    #include "Antistasi_chernarus_summer.chernarus_summer\navGrid.hpp"
    #include "Antistasi_chernarus_winter.chernarus_winter\navGrid.hpp"
    #include "Antistasi_Enoch.Enoch\navGrid.hpp"
    #include "Antistasi_Kunduz.Kunduz\navGrid.hpp"
    #include "Antistasi_Malden.Malden\navGrid.hpp"
    #include "Antistasi_sara.sara\navGrid.hpp"
    #include "Antistasi_Stratis.Stratis\navGrid.hpp"
    #include "Antistasi_takistan.takistan\navGrid.hpp"
    #include "Antistasi_Tanoa.Tanoa\navGrid.hpp"
    #include "Antistasi_tem_anizay.tem_anizay\navGrid.hpp"
    #include "Antistasi_Tembelan.Tembelan\navGrid.hpp"
    #include "Antistasi_vt7.vt7\navGrid.hpp"
};
